### ISSUE TITLE
Error when background linting

### ISSUE THREAD

**Issue by jaimerod** [attenzione/SublimeLinter-scss-lint#34]
When I open the console and make a change I get this error.

    SublimeLinter: error in SublimeLinter daemon: 
    SublimeLinter: -------------------- 
    SublimeLinter: Traceback (most recent call last):
      File "C:\Users\hiiam\BitTorrent Sync\sync\portable\sublime-text\Data\Packages\SublimeLinter\lint\queue.py", line 57, in loop
        item = self.q.get(block=True, timeout=self.MIN_DELAY)
      File "./queue.py", line 175, in get
    queue.Empty
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Users\hiiam\BitTorrent Sync\sync\portable\sublime-text\Data\Packages\SublimeLinter\lint\queue.py", line 65, in loop
        self.lint(view_id, timestamp)
      File "C:\Users\hiiam\BitTorrent Sync\sync\portable\sublime-text\Data\Packages\SublimeLinter\lint\queue.py", line 111, in lint
        self.callback(view_id, timestamp)
      File "C:\Users\hiiam\BitTorrent Sync\sync\portable\sublime-text\Data\Packages\SublimeLinter\sublimelinter.py", line 119, in lint
        Linter.lint_view(view, filename, code, hit_time, callback)
      File "C:\Users\hiiam\BitTorrent Sync\sync\portable\sublime-text\Data\Packages\SublimeLinter\lint\linter.py", line 924, in lint_view
        linter.lint(hit_time)
      File "C:\Users\hiiam\BitTorrent Sync\sync\portable\sublime-text\Data\Packages\SublimeLinter\lint\linter.py", line 1367, in lint
        cmd = self.get_cmd()
      File "C:\Users\hiiam\BitTorrent Sync\sync\portable\sublime-text\Data\Packages\SublimeLinter\lint\linter.py", line 1119, in get_cmd
        return self.build_cmd()
      File "C:\Users\hiiam\BitTorrent Sync\sync\portable\sublime-text\Data\Packages\SublimeLinter\lint\linter.py", line 1169, in build_cmd
        cmd[0:1] = util.convert_type(os.path.abspath(path), [])
      File "./ntpath.py", line 590, in abspath
    TypeError: 'list' does not support the buffer interface
     
    SublimeLinter: --------------------

The command line works fine.

Is this still maintained?

**Comment by attenzione** [comment]
This issue should be addressed to SublimeLinter Package, not it's plugin.
