### ISSUE TITLE
Breaks on @at-root h3#{&}

### ISSUE THREAD

**Issue by Valid** [attenzione/SublimeLinter-scss-lint#47]
When using the selector `@at-root h3#{&}` I get the following:

````
Error: Parsing error at c:/users/jon/appdata/local/temp/SublimeLinter3-Jon/_base.sass: Please check validity of the block starting from line #126
    at module.exports (C:\Users\Jon\AppData\Roaming\npm\node_modules\sass-lint\lib\groot.js:21:11)
    at Function.sassLint.lintText (C:\Users\Jon\AppData\Roaming\npm\node_modules\sass-lint\index.js:36:13)
    at C:\Users\Jon\AppData\Roaming\npm\node_modules\sass-lint\index.js:89:21
    at Array.forEach (native)
    at Function.sassLint.lintFiles (C:\Users\Jon\AppData\Roaming\npm\node_modules\sass-lint\index.js:88:9)
    at detectPattern (C:\Users\Jon\AppData\Roaming\npm\node_modules\sass-lint\bin\sass-lint.js:15:18)
    at C:\Users\Jon\AppData\Roaming\npm\node_modules\sass-lint\bin\sass-lint.js:54:5
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\Jon\AppData\Roaming\npm\node_modules\sass-lint\bin\sass-lint.js:53:16)
    at Module._compile (module.js:570:32) 
````

The purpose of the selector is to append the tag (h3) to the previous selector.

For example:

````
.foo
  color: red
  @at-root h3#{&}
    font-size: 20px
````

This becomes

````
.foo { color: red; }
h3.foo { font-size: 20px; }
````

**Comment by attenzione** [comment]
this issue comes from linter `sass-lint`, not this plugin for Sublime. Please report issue [there](https://github.com/brigade/scss-lint)
