### ISSUE TITLE
Linter keeps crashing

### ISSUE THREAD

**Issue by ChainsawBaby** [attenzione/SublimeLinter-scss-lint#50]
I'm suddenly starting to get a crashed scsslint.
I installed latest scss-lint version, 0.57.0 from 0.56.0 and thought that was the issue, so I downgraded back to 0.56.0 but that didn't help.
The config file hasn't been changed either.

```
SublimeLinter: #34 scsslint style.scss ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/MartinBratteng/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/MartinBratteng/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 821, in lint
  File "lint.linter in /Users/MartinBratteng/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 905, in process_match
  File "linter in /Users/MartinBratteng/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-contrib-scss-lint.sublime-package", line 46, in reposition_match
AttributeError: 'NoneType' object has no attribute 'start'
```

**Comment by attenzione** [comment]
You have incorrect PseudoElement in your scss file. Can you provide part of source where it could be.

**Comment by ChainsawBaby** [comment]
Here's my scss file. It's probably cause by code from line 89

https://gist.github.com/ChainsawBaby/e4aa223456f3631328049c1adafac37e

**Comment by ChainsawBaby** [comment]
It's some old css from the project that I haven't refactored yet. I recently started working on this file, so that might be it?

**Comment by attenzione** [comment]
nope, because i've copied you source and successfully linted it with 0.56 and 0.57 
and this is strange :)
do you have 2.0.1 version of plugin?

**Comment by ChainsawBaby** [comment]
Yeah, I have v2.0.1 installed.
All sublime packages should be up to date I think

**Comment by attenzione** [comment]
I will update code a little, where I guess is error, but i don't sure.

**Comment by r3volution11** [comment]
I also have this issue and it happens with any SCSS file I have open.

**Comment by attenzione** [comment]
Your error is in SublimeLinter file, not in plugin. It can't resolve cmd. Report issue in SL repo
